kind: Deployment 
apiVersion: apps/v1
metadata:
  name: frontservice
  namespace: kube-test
  annotations:
    description: This service is related to the front app for sentiments
    kubernetes.io/change-cause: This is the very first release
  labels:
    app: front-app
    mode: dev
    owner: Rohit-Squareops
spec:
  selector:
    matchLabels:
      name:  frontselector
  replicas: 2
  minReadySeconds: 20
  strategy:
    type: Recreate
  template:
    metadata:
      name: frontpod
      labels:
        name:  frontselector
    spec: 
      containers:
        - name: front
          image: rohitsquareops/frontend
          imagePullPolicy: IfNotPresent
          ports: 
            - containerPort: 80
          resources:
            requests:
              cpu: '100m'
              memory: "200Mi"
            limits:
              cpu: '150m'
              memory: '300Mi'
    