kind: Service
apiVersion: v1
metadata:
  name:  service-front
spec:
  selector:
    name: frontselector
  #type:  NodePort
  #type: LoadBalancer
  ports:
    - name:  "80-80"
      port:  80
      targetPort:  80
      protocol: TCP
      #nodePort: 32099
